apiVersion: v1
kind: Service
metadata:
  name: dcops-ui
  namespace: dcops-system
  labels:
    app: dcops-ui
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: dcops-ui
