apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dcops-system

resources:
- namespace.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- secret.yaml
- deployment.yaml

images:
- name: netbox-controller
  newName: 10.177.76.220:5000/netbox-controller
  newTag: tilt

