apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netbox-controller
  labels:
    app: netbox-controller
rules:
- apiGroups:
  - dcops.microscaler.io
  resources:
  # IPAM resources
  - netboxprefixes
  - netboxroles
  - netboxtags
  - netboxaggregates
  - netboxvlans
  - netboxrirs
  - netboxipaddresses
  - netboxipranges
  - netboxvrfs
  - netboxroutetargets
  # Tenancy resources
  - netboxtenants
  - netboxtenantgroups
  # DCIM resources - Sites
  - netboxregions
  - netboxsitegroups
  - netboxlocations
  - netboxsites
  # DCIM resources - Devices
  - netboxdeviceroles
  - netboxmanufacturers
  - netboxplatforms
  - netboxdevicetypes
  - netboxdevices
  - netboxinterfaces
  - netboxmacaddresses
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - dcops.microscaler.io
  resources:
  # IPAM resources
  - netboxprefixes/status
  - netboxroles/status
  - netboxtags/status
  - netboxaggregates/status
  - netboxvlans/status
  - netboxrirs/status
  - netboxipaddresses/status
  - netboxipranges/status
  - netboxvrfs/status
  - netboxroutetargets/status
  # Tenancy resources
  - netboxtenants/status
  - netboxtenantgroups/status
  # DCIM resources - Sites
  - netboxregions/status
  - netboxsitegroups/status
  - netboxlocations/status
  - netboxsites/status
  # DCIM resources - Devices
  - netboxdeviceroles/status
  - netboxmanufacturers/status
  - netboxplatforms/status
  - netboxdevicetypes/status
  - netboxdevices/status
  - netboxinterfaces/status
  - netboxmacaddresses/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch

