apiVersion: dcops.microscaler.io/v1alpha1
kind: NetBoxRIR
metadata:
  name: arin
  namespace: default
spec:
  name: ARIN
  slug: arin
  description: Seeded Regional Internet Registry for private network aggregate examples
  comments: ARIN RIR entry for private network aggregate examples. Managed by DCops
    controller.
  driftDetection: true
  tags:
  - apiGroup: dcops.microscaler.io
    kind: NetBoxTag
    name: managed-by-dcops
    namespace: default
