apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dcops-system

resources:
# namespace.yaml is already defined in netbox-controller, so we don't include it here
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml

images:
- name: dhcp-controller
  newName: 10.177.76.220:5000/dhcp-controller
  newTag: tilt

