apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dcops-system

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: pxe-ipxe-scripts
    files:
      - artifacts/ipxe/cylon-resurrection.ipxe
      - artifacts/ipxe/localboot.ipxe

images:
  - name: pxe-server
    newName: 10.177.76.220:5000/pxe-server
    newTag: tilt
