apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dcops-system

resources:
# namespace.yaml is already defined in netbox-controller, so we don't include it here
- configmap.yaml
- deployment.yaml
- service.yaml

